alias du="du -hs *"
alias dug="du | grep -oE '([0-9\.]+G.*)'"
alias dum="du | grep -oE '([0-9\.]+M.*)'"
alias duk="du | grep -oE '([0-9\.]+K.*)'"
alias dub="du | grep -oE '([0-9\.]+B.*)'"
alias rzsh='source ~/.zshrc'
alias ezsh='vim ~/.zshrc'
alias pycfind='find . -name "*.pyc"'
alias pycdelete='pycfind --delete'
alias dkls="docker container ls -a"
alias dkps="docker container ps"
alias dklogs="docker container logs -f"
alias dkstart="docker container start"
alias dkstop="docker container stop"
alias dkrm="docker container rm"
alias dkrename="docker container rename"
alias dkrun="docker container run -d"
alias dkexec="docker container exec --it"
alias dkcup="docker-compose up -d"
alias dklogs="docker-compose logs -f"
